:: Enable GitHub pages deployed via GitHub Actions on all repos
:: Each repo gets two commands, one enables pages and one changes already-enabled pages to use GitHub Actions
:: As such, each repo will fail one of the two commands.
:: You can use UTIL-get-pages-urls to confirm the operation worked
@setlocal
@call config.cmd
gh api --method POST /repos/%DEPLOY_ORG%/arduino/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/aruco/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/daqmx/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/deeplabcut/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/ephys/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/ffmpeg/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/gui/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/harp/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/ironpython-scripting/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/machinelearning/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/mixer/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/movenet/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/numerics/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/pointgrey/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/pulsepal/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/pylon/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/python-scripting/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/sgen/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/sleap/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/spinnaker/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/tld/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/video/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/vimba/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/zeromq/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/bitalino/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/bpod/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/cleyemulticam/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/cmt/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/kinect/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/physics/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/realsense/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/ueye/pages -f "build_type=workflow"
gh api --method POST /repos/%DEPLOY_ORG%/vr/pages -f "build_type=workflow"

gh api --method PUT /repos/%DEPLOY_ORG%/arduino/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/aruco/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/daqmx/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/deeplabcut/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/ephys/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/ffmpeg/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/gui/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/harp/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/ironpython-scripting/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/machinelearning/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/mixer/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/movenet/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/numerics/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/pointgrey/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/pulsepal/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/pylon/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/python-scripting/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/sgen/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/sleap/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/spinnaker/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/tld/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/video/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/vimba/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/zeromq/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/bitalino/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/bpod/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/cleyemulticam/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/cmt/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/kinect/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/physics/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/realsense/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/ueye/pages -f "build_type=workflow"
gh api --method PUT /repos/%DEPLOY_ORG%/vr/pages -f "build_type=workflow"