@setlocal
@config.cmd
gh repo clone $DEPLOY_ORG/arduino || exit /b
gh repo clone $DEPLOY_ORG/aruco || exit /b
gh repo clone $DEPLOY_ORG/bitalino || exit /b
gh repo clone $DEPLOY_ORG/bpod || exit /b
gh repo clone $DEPLOY_ORG/cmt || exit /b
gh repo clone $DEPLOY_ORG/daqmx || exit /b
gh repo clone $DEPLOY_ORG/deeplabcut || exit /b
gh repo clone $DEPLOY_ORG/ephys || exit /b
gh repo clone $DEPLOY_ORG/ffmpeg || exit /b
gh repo clone $DEPLOY_ORG/gui || exit /b
gh repo clone $DEPLOY_ORG/harp || exit /b
gh repo clone $DEPLOY_ORG/ironpython-scripting || exit /b
gh repo clone $DEPLOY_ORG/kinect || exit /b
gh repo clone $DEPLOY_ORG/machinelearning || exit /b
gh repo clone $DEPLOY_ORG/mixer || exit /b
gh repo clone $DEPLOY_ORG/movenet || exit /b
gh repo clone $DEPLOY_ORG/numerics || exit /b
gh repo clone $DEPLOY_ORG/physics || exit /b
gh repo clone $DEPLOY_ORG/pointgrey || exit /b
gh repo clone $DEPLOY_ORG/pulsepal || exit /b
gh repo clone $DEPLOY_ORG/pylon || exit /b
gh repo clone $DEPLOY_ORG/python-scripting || exit /b
gh repo clone $DEPLOY_ORG/realsense || exit /b
gh repo clone $DEPLOY_ORG/sgen || exit /b
gh repo clone $DEPLOY_ORG/sleap || exit /b
gh repo clone $DEPLOY_ORG/spinnaker || exit /b
gh repo clone $DEPLOY_ORG/tld || exit /b
gh repo clone $DEPLOY_ORG/ueye || exit /b
gh repo clone $DEPLOY_ORG/video || exit /b
gh repo clone $DEPLOY_ORG/vimba || exit /b
gh repo clone $DEPLOY_ORG/vr || exit /b
gh repo clone $DEPLOY_ORG/zeromq || exit /b
